# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MusicSearch' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for MusicSearch
pod 'CustomTableViewPod2’, :git => 'https://github.com/vallal7/CustomTableViewPod2', :tag => ‘1.0.0’ 

  target 'MusicSearchTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MusicSearchUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
